name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3  # Using Node.js 20

      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          github_user_name: Timuuc  # Ensure this matches your GitHub username
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Commit and push the animation
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push

      - name: Upload the generated animation
        uses: actions/upload-artifact@v3  # Using Node.js 20
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
