name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day at midnight UTC
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4  # Updated to v4 for Node.js 20 support

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4 for Node.js 20 support
        with:
          python-version: '3.x'  # Ensure Python 3.x is used

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: Timuuc  # Ensure this matches your GitHub username

      - name: Create dist directory
        run: mkdir -p dist

      - name: Move Snake Animation
        run: mv github-contribution-grid-snake.svg dist/github-contribution-grid-snake.svg

      - name: Commit and push the animation
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate snake animation"
          git push

      - name: Upload the generated animation
        uses: actions/upload-artifact@v3  # Updated to v3 for Node.js 20 support
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
