name: Generate snake animation

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate Snake Animation
        uses: Platane/snk@master
        with:
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Output Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.gif
      - name: Output Snake Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-svg
          path: dist/github-contribution-grid-snake.svg
      - name: Push Snake Animation to GitHub
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m "Generate snake animation"
          git push
